### ISSUE TITLE
Couldn't add persistent volume claims

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/Scalable-Cassandra-deployment-on-Kubernetes#10]
The headless worked great. But when trying the stateful service, the persistent volumes were created successfully, but the persistent volume claim keeps showing pending, and never bound successfully.

**Comment by AnthonyAmanse** [comment]
What does it show when you execute this command: `kubectl get pv,pvc`

**Comment by cenyuzhang** [comment]
'get pv' shows all the 3 volumes created successfully, but 'get pvc' shows the claim is pending (after a long time"

**Comment by cenyuzhang** [comment]
here is a screenshot:

<img width="788" alt="screen shot 2017-10-09 at 1 38 09 pm" src="https://user-images.githubusercontent.com/17069714/31353188-2a076dd8-acf7-11e7-91b9-d063321561ad.png">

**Comment by AnthonyAmanse** [comment]
It looks like you are using a paid cluster on Bluemix Container service. The pvc will be provisioned dynamically which means you wouldn't need to create Persistent Volumes. The storage class (ibmc-file-bronze) will create that for you whenever a persistent volume claim is created. It should get provisioned in less than 5 minutes

**Comment by cenyuzhang** [comment]
I see. Should I just delete all the local volumes, and then rerun to create the statefulset? Thanks.

**Comment by cenyuzhang** [comment]
Just deleted all the local volumes, statefulset, and then rerun to create the statefulset. Didn't see any PV created automatically. The PVC still shows pending.

<img width="734" alt="screen shot 2017-10-09 at 1 56 12 pm" src="https://user-images.githubusercontent.com/17069714/31353832-a37592d8-acf9-11e7-9360-700a8beac3f1.png">

**Comment by AnthonyAmanse** [comment]
Can you do `bx cs cluster-get YOUR_CLUSTER_NAME`

It should show the addons in your cluster:
```
...
Addons
Name                   Enabled   
customer-storage-pod   true   
basic-ingress          true   
storage-watcher-pod    true   
```

**Comment by cenyuzhang** [comment]
It doesn't show the addon. How can I install it? Here is my screenshot:

<img width="743" alt="screen shot 2017-10-09 at 2 03 17 pm" src="https://user-images.githubusercontent.com/17069714/31354096-ab5f38a4-acfa-11e7-90d0-1cf10d1221f9.png">

**Comment by AnthonyAmanse** [comment]
Try updating the bx cli `bx plugin update container-service -r Bluemix`

**Comment by cenyuzhang** [comment]
Thanks. After updating the addon, I now do see the following. But I have tried to redeploy everything and still not working

<img width="230" alt="screen shot 2017-10-09 at 4 46 53 pm" src="https://user-images.githubusercontent.com/17069714/31359901-9a6d1568-ad11-11e7-9376-7df9b2b8609b.png">

**Comment by AnthonyAmanse** [comment]
Try doing `kubectl get pods -n kube-system` and let me know if there is a pod named `ibm-storage-watcher-[xxxxx]`

**Comment by cenyuzhang** [comment]
Yes, I do have a pod ibm-storage-watcher-2152805327-ccln6 running. Also every time, I run the statefulset creation, I did get a notification that a new storage order was approved, but not sure why I couldn't see the actual storage.

**Comment by AnthonyAmanse** [comment]
The problem might be on the Softlayer side. You cloud try manually creating a Persistent Volume that uses that file storage in softlayer. https://console.bluemix.net/docs/containers/cs_cluster.html#cs_cluster_volume_create

--- or ---

You can specify to not use the storage class (by setting annotation of storage class to empty) and use the `local-volumes.yaml`
You could modify the `cassandra-statefulset.yaml`
```
...
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      annotations:
        volume.beta.kubernetes.io/storage-class: ""
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

That should use the volumes created through `local-volumes.yaml` (It's not gonna be using the file storage in Softlayer)

**Comment by cenyuzhang** [comment]
Thanks. It did work. But when I scaled it to 4 replica sets, the other 3 crashed, not sure why. See screenshot below:

<img width="556" alt="screen shot 2017-10-09 at 5 58 38 pm" src="https://user-images.githubusercontent.com/17069714/31361936-9bbcaa78-ad1b-11e7-9630-a16e86f67584.png">

**Comment by AnthonyAmanse** [comment]
Any logs on the cassandra-1,2,3? `kubectl logs cassandra-1`. Also check for the cassandra service `kubectl get svc`

**Comment by cenyuzhang** [comment]
Thanks. The log files did show the error from the cassandra seed variable. If I comment it out, it works fine. Not sure if there is a better way to do it. Thanks.
