### ISSUE TITLE
Nodes join with other nodes across namespace boundaries

### ISSUE THREAD

**Issue by neverfox** [IBM/Scalable-Cassandra-deployment-on-Kubernetes#11]
I believe because the cluster name is fixed, it's doesn't seem possible to have separate clusters in different namespaces without them gossiping and joining a single cluster.

**Comment by cenyuzhang** [comment]
Thanks. I will close the issue.

**Comment by neverfox** [comment]
The seed node is different, but the cluster name was the same. I guess I didn't realize it would be able to circumvent k8s boundaries. However, I haven't had luck changing the cluster name environment variable to override it. I'm trying some tests to see if that's really what's going on.

**Comment by neverfox** [comment]
> You can configure the yaml files to suit your needs.

Do the environment variable overrides not work in this setup? I assumed they would still affect the base cassandra image as documented for it. If not, have you considered breaking the yaml files out into a K8S configmap so they can be mounted rather than baked in?

**Comment by neverfox** [comment]
False alarm. It turned out it was an issue with the seed node address. Sorry for the noise.
