### ISSUE TITLE
Test usage of hostPath PersistentVolume

### ISSUE THREAD

**Issue by shivahr** [IBM/Scalable-Cassandra-deployment-on-Kubernetes#17]
Bluemix Container service got its Kubernetes server version upgraded to v1.7.4 recently. After this upgrade, we started seeing issues with hostPath PersistentVolumes (PV) as reported in IBM/deploy-graph-db-container#3 (we had no such issues with the older v.1.5.x Kubernetes server version). Since this repo also uses hostPath PV, please test it out once and see if you need similar fix.

**Comment by mlangbehn** [comment]
@shivahr, thanks for mentioning this! I just took a look, and we have not had any issues in CI. Closing as we do not seem to be impacted by this issue. Please feel free to reopen and ping me if that is not the case.
